openapi: 3.0.0
info:
  title: Proxy Example
  version: 1.0.0
servers:
- url: https://3y3.dev
paths:
  /docs/{path+}:
    get:
      x-yc-apigateway-integration:
        headers:
          x-real-host: 3y3.dev
          x-docs-proxy-base: docs
          x-docs-project-name: diplodoc-platform--docs
        http_method: get
        query:
          '*': '*'
        type: http
        url: https://diplodoc-platform--docs.viewer.diplodoc.com/{path}
      parameters:
        - name: path
          in: path
          required: false
          schema:
            type: string